---
- name: Create tmp directory
  ansible.builtin.file:
    path: "{{ tmp_path }}"
    mode: "0755"
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
