---
- name: Create java directory
  ansible.builtin.file:
    path: "{{ tmp_path }}/java-{{ java_version }}"
    mode: "0755"
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"

- name: Extract Java
  ansible.builtin.unarchive:
    src: "{{ tmp_path }}/java-{{ java_version }}.tar.gz"
    dest: "{{ tmp_path }}/java-{{ java_version }}"
    mode: "0755"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
