---
- name: Create tmp java directory
  ansible.builtin.file:
    path: "{{ tmp_path_java }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"

- name: Extract Java
  ansible.builtin.unarchive:
    src: "{{ tmp_path_java_tar }}"
    dest: "{{ tmp_path_java }}"
    mode: "0755"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
